### ISSUE TITLE
Typo when talking about `strip_only_modified_lines` variable in README

### ISSUE THREAD

**Issue by evanrelf** [ntpeters/vim-better-whitespace#105]
In the README you say:

> By default, all the lines in the file will have their trailing whitespace stripped when you save the file. This can be changed to only the modified lines, by adding the following to your ~/.vimrc:
> `let g:strip_only_modified_lines=0`

And in the Vim help/doc you say:

> If `g:strip_only_modified_lines` is set to 1, only modified lines will be stripped.

I think it should be `1` in the README.

**Comment by ntpeters** [comment]
Resolved in #121
