### ISSUE TITLE
let g:better_whitespace_filetypes_blacklist = ['help'] doesn't work

### ISSUE THREAD

**Issue by astier** [ntpeters/vim-better-whitespace#108]
> NVIM v0.3.5

Whitespace is shown in a help-buffer despite blacklisting *help*:

```
let g:better_whitespace_filetypes_blacklist = ['help']
```

According to the documentation it should also be blacklisted by default. I tried the following minimal vimrc for the gutentags help-file.

```
call plug#begin('~/.local/share/nvim/plugins')
Plug 'ludovicchabant/vim-gutentags'
Plug 'ntpeters/vim-better-whitespace'
call plug#end()
let g:better_whitespace_filetypes_blacklist = ['help']
```
 The whitespace is shown in the gutentags help-file on line 466. I also observed it  in other help-files like from the coc-plugin.

**Comment by Cimbali** [comment]
It appears that `help` pages get first detected as being `text`, and only later does the filetype get updated to `help`. So when text is detected we decide to enable the whitespace highlighting, and that decision is taken once only.

As a workaround for now you can force disabling the whitespace on `help` filetypes by adding the following to your vimrc:

    au FileType help DisableWhitespace

**Comment by astier** [comment]
Is this a vim-bug or on purpose? If its a bug maybe you should report it.

**Comment by oblitum** [comment]
Maybe this is related to #125.
