### ISSUE TITLE
StripWhitespace still works in blacklisted file

### ISSUE THREAD

**Issue by harriott** [ntpeters/vim-better-whitespace#114]
I can open a `markdown` file in which the whitespaces aren't highlighted, and `:StripWhitespace`, and they're all gone, without any visible sign that they've been removed. A little risky...

The fix would be to also disable the `StripWhitespace` function for blacklisted files.

**Comment by Cimbali** [comment]
I mean, the `StripWhitespace` command strips whitespace, why is that so weird? I suggest if you don't want to remove whitespace to not use that command...

It's a normal use case to remove whitespace in a file where you don't want to display it, be it manually or with autocommands, so I don't think we should disable the command on blacklisted files.

**Comment by harriott** [comment]
That's a good point, but you should change your README accordingly. As it is, you have written, "To disable this plugin for specific file types...", but the plugin is not disabled by the blacklist, just the highlighting of whitespaces. Your README needs to state that.

When I've some time, I'll look again, see if I can add the full disabling, as I'd prefer, in a fork.

A minor point of readability: just below the contested statement, you've "If you do not want any of these filetypes unignored" which I suggest you change to "If you prefer to also keep these default filetypes ignored" - to avoid the double negative.

**Comment by ntpeters** [comment]
Resolved in #121
