### ISSUE TITLE
HEX colors don't work

### ISSUE THREAD

**Issue by blasco** [ntpeters/vim-better-whitespace#116]
I've tried this:

let g:better_whitespace_ctermcolor = '#FF0000'
let g:better_whitespace_guicolor = 'gray'

But this is the result:

![Screenshot_2019-10-09_16-27-44](https://user-images.githubusercontent.com/3214400/66490621-bcd99d80-eab1-11e9-88a5-b1aa52ddfc9a.png)

**Comment by Cimbali** [comment]
I'm not sure vim supports hex colors. Try using a color name that is close, e.g. "red" for #FF0000. See https://vimhelp.org/syntax.txt.html#cterm-colors for a short list of supported colors. Depending on your terminal there might be more.
