### ISSUE TITLE
Add feature to automatically strip modified lines only

### ISSUE THREAD

**Issue by alerque** [ntpeters/vim-better-whitespace#124]
The [vim-strip-trailing-whitespace](https://github.com/axelf4/vim-strip-trailing-whitespace) plugin has an ingenious feature for only modifying lines that are changed for other reasons manually. It would be lovely to see that  feature integrated here.

Crosslink: https://github.com/axelf4/vim-strip-trailing-whitespace/issues/2

**Comment by sQVe** [comment]
@alerque Is this not the same thing as running this plugin with the `let g:strip_only_modified_lines = 1` setting?

**Comment by alerque** [comment]
Doh! I was unaware of that feature, even having searched for it. Probably a typo in my search. Yes that's what I wanted to accomplish.

Thanks for the pointer.
