### ISSUE TITLE
Disable in floating windows by default

### ISSUE THREAD

**Issue by oblitum** [ntpeters/vim-better-whitespace#125]
Floating windows, both in NeoVim and Vim, are generally read-only, for some kind of code assistance, but vim-better-whitespace is still enabled in them, which isn't much useful, and may just clutter such windows.

**Comment by Cimbali** [comment]
Apparently [checking &buftype == 'popup'](https://vimhelp.org/popup.txt.html#popup-buffer) would be enough.

**Comment by Cimbali** [comment]
Does that commit work for you @oblitum ?

**Comment by oblitum** [comment]
Sadly it didn't work for the floating window I'm having issues with in NeoVim. The `buftype` for it seems to be `nofile`, which is part of the check already, but it has no effect on the floating window,  which is full of red whitespace at the moment.
![21:45:44_15-01-2020](https://user-images.githubusercontent.com/1269815/72483633-6c748900-37e0-11ea-960b-c4b89b452191.png)

**Comment by oblitum** [comment]
The floating window comes from [coc-actions](https://github.com/iamcco/coc-actions), while coding with `coc-rust-analyzer`.

**Comment by roachsinai** [comment]
Hi, please diable in terminal buftype, too. As when use `<c-\><c-n>` to change a terminal buffer to `TERMINAL N` there are highlights for trailing spaces.

```
    if !exists('b:better_whitespace_enabled') && g:better_whitespace_enabled == 1 && !(empty(&buftype) && empty(&filetype))
        let b:better_whitespace_enabled = &buftype != 'nofile' && &buftype != 'terminal' && index(g:better_whitespace_filetypes_blacklist, &ft) == -1
    endif
```

patch above doesn't work either, as `!exists('b:better_whitespace_enabled')` return `0`, so if statement is skipped.

Thanks in advance!

**Comment by roachsinai** [comment]
@oblitum maybe you could use `['diff', 'gitcommit', 'vim-plug', '']` (check `''`) as blacklist.

**Comment by oblitum** [comment]
@roachsinai doesn't work, see https://github.com/ntpeters/vim-better-whitespace/issues/130#issuecomment-612439933.

**Comment by roachsinai** [comment]
Hi, I wish diable in terminal buftype, too. As when use `<c-\><c-n>` to change a terminal buffer to `TERMINAL N` there are highlights for trailing spaces.

```
    if !exists('b:better_whitespace_enabled') && g:better_whitespace_enabled == 1 && !(empty(&buftype) && empty(&filetype))
        let b:better_whitespace_enabled = &buftype != 'nofile' && &buftype != 'popup' && index(g:better_whitespace_filetypes_blacklist, &ft) == -1
    endif
```

What I found is patch above doesn't work seems `!exists('b:better_whitespace_enabled')` return `0`, so if statement is skipped.
