### ISSUE TITLE
Highlight failure

### ISSUE THREAD

**Issue by Calm-cpy** [ntpeters/vim-better-whitespace#128]
When blank character highlighting is set, if floating window appears, the highlighting will be invalid, and it will not be restored until entering the insertion mode again.

**Comment by Cimbali** [comment]
Hi @Calm-cpy, thanks for reporting this issue.

Could you specify what you mean by floating window? Is this a vim `popup` buffer or a neovim buffer? Can you also give an example of what you do to open the floating window?

**Comment by Calm-cpy** [comment]
Didn't reply in time due to time difference. It's vim popup. 
About floating window:
![2020-03-24_9-14-20](https://user-images.githubusercontent.com/48640489/77378213-58d13a00-6db0-11ea-8cd9-43dcd5443297.png)
"error" is an illegal character. I put two spaces after "error". When the cursor moves to error, my language check plug-in will pop up float windows to display the error message. When pop up the float window, all highlights will fail. 
![2020-03-24_9-13-19](https://user-images.githubusercontent.com/48640489/77378551-355abf00-6db1-11ea-95f2-02a9a940e79b.png)
After re entering the insertion mode, the blank character will be highlighted again. 
My configuration is as follows：
    let g:better_whitespace_enabled=1
    let g:strip_whitespace_on_save=0
    let g:current_line_whitespace_disabled_hard=0

If the configuration is modified as follows, the highlighting of the blank string will be restored automatically. But there are other problems. 
    let g:better_whitespace_enabled=1
    let g:strip_whitespace_on_save=0
    let g:current_line_whitespace_disabled_soft=1
![8~BPBWIZD(BCH5VBLR6T2}O](https://user-images.githubusercontent.com/48640489/77378902-4ce67780-6db2-11ea-9e78-3906405f9f49.png)

Thank you for your attention

**Comment by Calm-cpy** [comment]
Just tested, the gray highlight in the third figure is the problem of syntax error checking plug-in. It's not about VIM better whitespace

**Comment by Cimbali** [comment]
Which plugin do you use for language errors?

**Comment by Calm-cpy** [comment]
neoclide/coc.nvim

**Comment by Calm-cpy** [comment]
dense-analysis/ale

**Comment by Cimbali** [comment]
Alright, I seem to be able to reproduce this on vim 8.1. The `BufEnter` and `BufWinEnter` do not get fired when the popup opens or closes.

**Comment by Cimbali** [comment]
We disable the highlighting from the `BufWinLeave` which is called from the popup, but for the wrong buffer:

	BufWinLeave			Before a buffer is removed from a window.
					Not when it's still visible in another window.
					Also triggered when exiting.  It's triggered
					before BufUnload or BufHidden.
					NOTE: When this autocommand is executed, the
					current buffer "%" may be different from the
					buffer being unloaded "<afile>".
					When exiting and v:dying is 2 or more this
					event is not triggered.

We should either check it is the correct buffer, or remove this event altogether.

**Comment by ntpeters** [comment]
@Cimbali thanks for the quick investigation and fix for this, you rock! 😀

@Calm-cpy the fix from Cimbali is merged in now, can you update and give it a try?

**Comment by Calm-cpy** [comment]
The problem has been fixed very well. Now I'm going to use it to enjoy programming. Thanks. :blush:
