### ISSUE TITLE
whitespaces in leaderguide window

### ISSUE THREAD

**Issue by ScrumpyJack** [ntpeters/vim-better-whitespace#133]
is there a way of getting better-whitespace to ignore the leaderguide window?

<img width="1436" alt="leader" src="https://user-images.githubusercontent.com/3187469/83122642-d88ac600-a0cb-11ea-99ab-48f5413cd1a8.png">

**Comment by Cimbali** [comment]
I’m afraid I’m not sure what the leaderguide window is, but there are several ways to disable better-whitespace:
- adding the filetype to `g:better_whitespace_filetypes_blacklist`
- adding an autocommand matching this window that calls `DisableWhitespace`
- disabling better-whitespace by default and only enabling it only on files where you actually want it

I think most of this is detailed in the README or better whitespace help page if you need additional details.

**Comment by ScrumpyJack** [comment]
Leaderguide is a plugin that creates a sort of menu with your key mappings.

https://github.com/hecal3/vim-leader-guide

I think autocommand is what I want. Thanks for your response.

**Comment by Cimbali** [comment]
I think this can be closed @ntpeters
