### ISSUE TITLE
Don't strip on InsertLeave write with nested events

### ISSUE THREAD

**Issue by xerus2000** [ntpeters/vim-better-whitespace#135]
I have the following configuration:
```vim
let g:strip_whitespace_on_save=1
autocmd FocusLost,InsertLeave,BufLeave * ++nested write
```
I would like this plugin to not strip whitespace if it is triggered by the above autocmd.

**Comment by Cimbali** [comment]
Well the easiest way is to remove the `++nested` of course, but I suppose you need it for something. You could save `b:better_whitespace_enabled` and set it to `0` before the write, and restore it afterwards.

**Comment by xerus2000** [comment]
Yes indeed, I need it for firenvim. I tried it, but it still asks me to strip whitespace on save:

```vim
	autocmd FocusLost,InsertLeave,BufLeave * ++nested call WriteSilent()
	function WriteSilent()
 		let tmp=b:strip_whitespace_on_save
		let b:strip_whitespace_on_save=0
		call write
		let b:strip_whitespace_on_save=tmp
	endfunction
```

**Comment by xerus2000** [comment]
Also tried to set "better_whitespace_enabled", no success either.

**Comment by xerus2000** [comment]
Maybe related to https://github.com/ntpeters/vim-better-whitespace/issues/134

**Comment by Cimbali** [comment]
> Yes indeed, I need it for firenvim. I tried it, but it still asks me to strip whitespace:
> 
> ```viml
> 	autocmd FocusLost,InsertLeave,BufLeave * ++nested call WriteSilent()
> 	function WriteSilent()
>  		let tmp=b:strip_whitespace_on_save
> 		let b:strip_whitespace_on_save=0
> 		write
> 		let b:strip_whitespace_on_save=tmp
> 	endfunction
> ```

Ah yes, if this variable is true then we set the autocommand on BufWritePre and otherwise we don’t. There is no condition checking inside the BufWritePre handler. The following should work:
```viml
autocmd FocusLost,InsertLeave,BufLeave * ++nested call WriteSilent()
function WriteSilent()
	let was_enabled=b:strip_whitespace_on_save
	DisableStripWhitespaceOnSave
	write
        if was_enabled | EnableStripWhitespaceOnSave | endif
endfunction
```

**Comment by xerus2000** [comment]
![image](https://user-images.githubusercontent.com/13354331/88522067-22255d80-cff6-11ea-957c-e978e75d0295.png)
I had to replace the pipes with linebreaks, but it works now, thanks :)

**Comment by xerus2000** [comment]
or, even simpler:
```vim
	autocmd FocusLost,InsertLeave,BufLeave * ++nested call WriteSilent()
	function WriteSilent()
		let was_enabled=b:strip_whitespace_on_save
		DisableStripWhitespaceOnSave
		write
		&was_enabled && EnableStripWhitespaceOnSave
	endfunction
```
