### ISSUE TITLE
How to disable this plugin in Fugitive status buffer?

### ISSUE THREAD

**Issue by cyrus-and** [ntpeters/vim-better-whitespace#137]
Here's a minimal `.vimrc` containing my attempt:

```vim
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

Plugin 'ntpeters/vim-better-whitespace'
let g:better_whitespace_filetypes_blacklist = ['fugitive']
let g:better_whitespace_enabled = 1

Plugin 'tpope/vim-fugitive'

call vundle#end()
```

Reproduce it with the following:

```console
cd $(mktemp -d)
git init
echo >foo
git add foo
git commit -m foo
echo >>foo
vim
```

Then, inside Vim, `:G`, `<C-N>`, `=`. The outcome is:

<img width="194" alt="Screenshot 2020-07-01 at 3 37 11 PM" src="https://user-images.githubusercontent.com/1660263/86250428-d9be7f80-bbb0-11ea-9aea-4d1990894561.png">

**Comment by Cimbali** [comment]
What's the `&filetype` in this buffer?

**Comment by cyrus-and** [comment]
```
:set filetype?
filetype=fugitive
```

**Comment by cyrus-and** [comment]
OK this happens in VIM 8.1 (macOS) but not on VIM 8.2 (Homebrew).

**Comment by cyrus-and** [comment]
> OK this happens in VIM 8.1 (macOS) but not on VIM 8.2 (Homebrew).

Well, no that's not exactly true, it's sufficient to refresh the content of the Fugitive buffer as a last step (`:e`) to trigger the issue again, even with VIM 8.2.

**Comment by Cimbali** [comment]
So this is possibly similar to #108. Some corner cases of setting the filetype slip by our detection. In particular we don’t toggle on new filetypes once the detection is done. I think there was a reason for that − not quite sure what it was anymore off the top of my head.

Anyways, maybe the workaround there also works for you, in the mean time:

    au FileType fugitive DisableWhitespace

**Comment by cyrus-and** [comment]
Thanks it actually works.

**Comment by Cimbali** [comment]
Closing as this issue is tracked in #108
