### ISSUE TITLE
blacklist not working for help files

### ISSUE THREAD

**Issue by oblitum** [ntpeters/vim-better-whitespace#139]
Enabled anytime I call `:h something`, which affects help of some plugins I use, `'help'` on blacklist has no effect.

**Comment by oblitum** [comment]
Possibly related to #130.

**Comment by Cimbali** [comment]
Possibly a duplicate of #108 ? With a workaround in there until someone gets around to improving filetype detection.

**Comment by Cimbali** [comment]
Closing for now, feel free to reopen @oblitum if I missed something and this is somehow different.

**Comment by oblitum** [comment]
Ah, indeed, sorry for the noise, I did even commented on that issue and completely forgot about it.
