### ISSUE TITLE
Remove Whitespace search pattern from search history completely

### ISSUE THREAD

**Issue by c02y** [ntpeters/vim-better-whitespace#146]
I'm using neovim v.0.4.4

The history file is `~/.local/share/nvim/shada/main.shada`, once I execute `:StripWhitespace` automatically or manually, the following part will be appended into the history file:
```
History entry with timestamp 2021-04-22T09:34:42:
    @ Description_  Value
    - history type  SEARCH
    - contents      "[\\u0009\\u0020\\u00a0\\u1680\\u180e\\u2000-\\u200b\\u202f\\u205f\\u3000\\ufeff]\\+$"
    - separator     '\0'
```
It is very annoying when I try to search the previous string from the history file.

Is this a bug or how can avoid it?

**Comment by Cimbali** [comment]
We specifically save and restore the latest search `@/` when stripping whitespace, so it shouldn't interfere with what you are doing when cleaning whitespace. I don't know that we can avoid having it in history at all.

**Comment by c02y** [comment]
> Q: I already have my own method of removing white space, why is the method used in this plugin better?

> A: It may not be, depending on the method you are using. The method used in this plugin strips extra white space and then restores the cursor position and last search history.

in README, does it mean this problem is avoided? But it is still there.

**Comment by Cimbali** [comment]
Might not be phrased ideally. Your last search and cursor position are restored.

**Comment by Cimbali** [comment]
Alright @c02y try the version at 50623d6, I haven’t tested it in depth but it seems to do what you expect. After calling `StripWhitespace` the better whitespace patterns don’t show up in my search history window (`q/`).

**Comment by c02y** [comment]
I got two problems:
1. the `let g:strip_whitespace_on_save=1` seems not to work at all, neither old commit(8cf4b2175dd, installed using vim-plug, the only one commit) or the new commit edition, I have to call `:StripWhitespace` manually
2. the https://github.com/ntpeters/vim-better-whitespace/commit/50623d64e207e5df4059d4ea31c7753241520924 which only shows three modifications, but the whole file has more than my local file, I replace the file completely, the bug seems fixed.

This is my config:
```
    Plug 'ntpeters/vim-better-whitespace'
    let g:better_whitespace_enabled=1
    let g:strip_whitespace_on_save=1
    let g:show_spaces_that_precede_tabs=1
```

**Comment by Cimbali** [comment]
That commit also includes PR #140 which reworks file-type detection, which is why you see more changes. Whether you just import that single commit (i.e. those changes) or the file at that revision, the search history should not contain better whitespace’s search patterns anymore.

Not sure about the other problem, but it sounds like a bug, so you can open a new issue about that. Please report there minimal configuration to reproduce the bug (which helps to make sure other settings are not interfering, e.g. stripping whitespace on changed lines only).

**Comment by c02y** [comment]
Thanks, I'll close this issue then.

**Comment by Cimbali** [comment]
Well I like the improvement and it's not merged yet, let's leave it open for now and see what @ntpeters thinks of it.
