### ISSUE TITLE
Never strip whitespace in markdown files but highlight it

### ISSUE THREAD

**Issue by mrolli** [ntpeters/vim-better-whitespace#149]
As a markdown writer, I never want to have Vim strip whitespace especially from line ends. But as trailing whitespace has special meaning, I want to be able to still highlight these to be able to immediately identify these "forced line breaks".

From what I see in the code, highlighting and stripping are married with the blacklist, aren't they. Either highlight && strip  or no highlight && no strip. If yes, then the first paragraph is a feature request. If no, then could this is a question and I'd like to be guide to a proper configuration then.

**Comment by Cimbali** [comment]
You can always use autocommands to tweak the settings. For example here, to disable strip whitespace on save on markdown filetypes:

```vimL
:au FileType markdown DisableStripWhitespaceOnSave
```

You’ll need to remove the `markdown` from the (updated) default blacklist though.


```vimL
let g:better_whitespace_filetypes_blacklist=['diff', 'git', 'gitcommit', 'unite', 'qf', 'help', 'fugitive']
```

**Comment by mrolli** [comment]
Thank you for the two suggested configuration changes and pointing to autocommands. Works as suggested.
