### ISSUE TITLE
Error detected while processing BufWritePre Autocommands for "*"..function <SNR>23_StripWhitespaceOnSave

### ISSUE THREAD

**Issue by asgeo1** [ntpeters/vim-better-whitespace#160]
I'm getting this error when saving a file in Vim:

> Error detected while processing BufWritePre Autocommands for "*"..function <SNR>23_StripWhitespaceOnSave

I think about 2 weeks ago, I updated my plugins and everything was fine. And today I've updated them again, and now I get this error. It's weird, because looking at this repo, it doesn't look like anything has changed.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/702212/206933725-c77e8f7e-a0bf-499d-960d-f9135dfc31e2.png">

I've tried to isolate the issue by removing every plugin (other than vim-better-whitespace), and pretty much commenting out my entire Vim setup, other than packer.

I still get the same error, which is really weird. Any ideas?

This is how I am using this plugin in my packer setup:

```lua
    use {
        'ntpeters/vim-better-whitespace',
        config = function()
          vim.g.strip_whitespace_on_save = 1
          vim.g.better_whitespace_filetypes_blacklist = {
            'spectre_panel',
            'diff',
            'git',
            'gitcommit',
            'unite',
            'qf',
            'help',
            'markdown',
            'fugitive',
          }
          vim.g.strip_whitespace_confirm = 0
          vim.g.show_spaces_that_precede_tabs = 1
          vim.g.better_whitespace_operator = '_s'
          vim.g.strip_only_modified_lines = 1
        end,
      }
```

**Comment by Cimbali** [comment]
Hi @asgeo1, can you give details of your platform, vim version, plugin manager, etc? Seeing the error and when it happens I think it could be your `diff` command that changed. You should be able to set it using `vim.g.diff_binary`

**Comment by kstevens715** [comment]
I get this same error. I thought I first saw it after upgrading to Neovim nightly. But I also just tried it and reproduced it with versions 0.7.2, 0.8.0 and 0.8.1.

I'm using a Mac and Packer as my plugin manager. Here's some info about my current Neovim version:

```
NVIM v0.9.0-dev-415+g282dda643-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by Cimbali** [comment]
Does the error disappear if you set `g:strip_only_modified_lines=0` ? If so, what are the outputs of `command diff --version` and `which -a diff` ?

**Comment by kstevens715** [comment]
Yes, setting `g:strip_only_modified_lines=0` does make the error go away.

Here's the output of those commands:

```
➜  dotfiles git:(master) ✗ command diff --version
Apple diff (based on FreeBSD diff)
➜  dotfiles git:(master) ✗ which -a diff
/usr/bin/diff
```

**Comment by kstevens715** [comment]
If I replace Apple diff with GNU diffutils (`brew install diffutils`) the problem also goes away.

**Comment by Cimbali** [comment]
yes so this is the same as #159. If you use GNU diff (`brew install diffutils`) then you’ll be able to keep `strip_only_modified_lines=1`. I’m not sure why this seems to change for several users at the same time.
