### ISSUE TITLE
This plugin blows away existing highlights

### ISSUE THREAD

**Issue by nullromo** [ntpeters/vim-better-whitespace#162]
## Problem

When switching windows, this plugin removes matches that it shouldn't be removing.

## Desired Behavior

This plugin should never delete any matches that it did not create.

## Steps to Reproduce

0. Open vim

Follow these keystrokes:

1. `ifoo<Esc>` (insert the text "foo")
2. `:vnew<Enter>` (create a new window)
3. `:highlight MyTestGroup guibg=white<Enter>` (create a highlight group)
4. `:echo matchadd('MyTestGroup', 'foo', 10, -1, {'window': 1000})<Enter>` (create a match in the first window that matches the text and highlights it)
5. `<C-w>l` (switch back to the first window)

Notice that the match is now gone.

## Cause

Because the variable `s:match_id` is script-scoped, it doesn't change once it's set. Once this plugin gets a match ID (always `1020` in my case; not sure if it can be different) from `matchadd`, it keeps on using that match ID forever. If you ever set up a match in a window that doesn't have the ID=1020 match active, `matchadd` will automatically choose 1020. Then this plugin will later call its `ClearHighlighting()` function and delete the match with ID 1020, even though it shouldn't.

## Solution

I think you need to track the match ID for each window separately instead of globally reserving ID 1020 for this plugin. Otherwise other code that uses Vim's match feature will not work properly.

**Comment by Goorzhel** [comment]
I'm not fluent in Vimscript, but is it possible that the first commit in #161 will fix this?

**Comment by Cimbali** [comment]
Seems likely indeed, the handling of match ids is made per-window as it should be.

**Comment by nullromo** [comment]
I confirmed that this does fix the problem. I manually copied the code from commit [a0a602e0](https://github.com/ntpeters/vim-better-whitespace/commit/a0a602e0f3803b44269ac8742c2950cf61fa2300) into my local tree and tested the steps above. The match highlighting remains in place, as it should.

However, it looks like #161 is awaiting review.
