### ISSUE TITLE
Highlight stops working for a line when chars are added and then removed after trailing spaces

### ISSUE THREAD

**Issue by dhananjaylatkar** [ntpeters/vim-better-whitespace#165]
Steps to repro -
1. Add trailing spaces and go to normal mode. => Highlights perfectly
2. Add chars after tailing spaces => Highlight removed as expected
3. Add trailing spaces after new chars and go to normal mode => **No highlight**
4. remove all trailing spaces and new chars from that line and add trailing spaces again => **No Highlight**
5. Add trailing spaces on other line => Highlight works

Check this Screencast -
[Screencast](https://github.com/ntpeters/vim-better-whitespace/assets/27724944/1d21f8d7-b017-40b4-923d-186c56067b2b)

My config -
```lua
vim.g.better_whitespace_enabled = 1
vim.g.better_whitespace_filetypes_blacklist = { "dashboard" }
```

**Comment by Cimbali** [comment]
What’s your neovim version? This doesn’t seem to happen in vim.

**Comment by dhananjaylatkar** [comment]
➜ nvim --version
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794
Compilation: /usr/bin/gcc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DUSING_UV_SHARED=1 -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include/luv -I/builddir/build/BUILD/neovim-0.9.5/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.9.5/redhat-linux-build/include -I/builddir/build/BUILD/neovim-0.9.5/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.9.5/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

**Comment by Cimbali** [comment]
Does it happen if vim-better-whitespace is the only plugin loaded?
