### ISSUE TITLE
Show highlights but don't strip whitespace for blacklisted files

### ISSUE THREAD

**Issue by nickjj** [ntpeters/vim-better-whitespace#169]
Hi,

I currently have this configuration:

```vim
let g:strip_whitespace_confirm=0
let g:strip_whitelines_at_eof=1
let g:strip_whitespace_on_save=1
let g:better_whitespace_filetypes_blacklist=["diff", "git", "gitcommit", "unite", "qf", "help", "markdown", "liquid.markdown", "fugitive"]
```

Functionality wise with saves everything is working. Whitespace doesn't get stripped for those blacklisted file types.

However, I'd like to visually see whitespace highlights for those blacklisted files so I know they exist.

For example I write a lot of Markdown and it's useful to see 2 trailing spaces for a `<br>`. I don't want it stripped on save with my current configuration but I always want to know it's there.

Is there anything I can configure for that? Thanks.

**Comment by Cimbali** [comment]
I’d remove it from the blacklist, then add the following to your config:
```vim
au FileType markdown DisableStripWhitespaceOnSave
```

**Comment by nickjj** [comment]
Hey, thanks a lot. That's perfect.
