### ISSUE TITLE
Feature request: adding an operator for `:StripWhitespace`

### ISSUE THREAD

**Issue by bruno-** [ntpeters/vim-better-whitespace#18]
Hi,
thanks for the great plugin! What do you think about adding an operator that would work with `:StripWhitespace` command?

The end result would be something like this:
- `d<space>ip` - would "StripWhitespace" for 'inner paragraph'
- `d<space>G` - would strip whitespace till the end of the file
- etc for all other vim motions

The `d<space>` operator would be nice because it's a mnemonic for "delete space" and fits nicely in vim's vocabulary.

This shouldn't be too hard to make and I'd gladly do it - if you think it's a feature worth accepting into the repo?

Thanks

**Comment by ntpeters** [comment]
Hey, this is a cool idea.  The only thing I'd say is to maybe have a way to easily disable the operator from being setup for people out there who don't want plugins messing with their key mappings. What do you think?

I like the idea though, so if you threw a pull request my way I'd accept it!
