### ISSUE TITLE
Highlighting of extra whitespace fails, when a tab is closed.

### ISSUE THREAD

**Issue by martong** [ntpeters/vim-better-whitespace#20]
Steps to reproduce:
*) Open a file with white spaces. White spaces are highlighted.
*) :tabe someotherfile
*) `<C-W>c` 
   At this point you are seeing the first opened file, but white spaces are not highlighted.

**Comment by ntpeters** [comment]
I am currently unable to reproduce this.  Could you see if this is still an issue for you in the current version?
