### ISSUE TITLE
Unoptimized <SID>SetupAutoCommands() calls

### ISSUE THREAD

**Issue by noscript** [ntpeters/vim-better-whitespace#21]
I noticed ```<SID>SetupAutoCommands()``` gets called on vim startup at least four times in a row. Every other buffer switch causes it to be called another two times sequentially instead of a single call. Is that really necessary?

**Comment by hermes85pl** [comment]
I am sorry to tell you that the fix introduced a flow: having configured vim-better-whitespace to ignore "vimfiler" filetype, I get all the trailing whitespace highlited when opening a vimfiler buffer for the first time by calling ":VimFiler -explorer" (this does not happen after closing the window and calling it again).
