### ISSUE TITLE
enable ToggleStripWhitespaceOnSave in .vimrc

### ISSUE THREAD

**Issue by Futile** [ntpeters/vim-better-whitespace#25]
I would like to enable stripping of whitespace for all file types by default in my `.vimrc`, and putting `ToggleStripWhitespaceOnSave` in a line after `Plugin 'ntpeters/vim-better-whitespace'` does not work.

**Comment by ntpeters** [comment]
I'm assuming you're using Vundle, from the sounds of it.
If so, you need to have the line setting whitespace stripping after your `call vundle#end()` line.

**Comment by Futile** [comment]
> I'm assuming you're using Vundle, from the sounds of it.

Yep.

> If so, you need to have the line setting whitespace stripping after your call vundle#end() line.

Like this?

```vim
Plugin 'ntpeters/vim-better-whitespace'
call vundle#end()
ToggleStripWhitespaceOnSave
```

Doesn't work either, still gives me `E492: Not an editor command: ToggleStripWhitespaceOnSave` when starting vim.

**Comment by ntpeters** [comment]
Ah, I was on my phone and totally overlooked the command you were entering.
You need to tell Vim to call that command, like so:
```
au VimEnter * ToggleStripWhitespaceOnSave
```
This will cause Vim to call `ToggleStripWhitespaceOnSave` automatically after it completes its startup.

**Comment by Futile** [comment]
Ah, that works, thanks!

**Comment by hackel** [comment]
I think it's probably better to just add `let strip_whitespace_on_save = 1` to .vimrc.  Would be useful to add this to the docs as well.

**Comment by mooreniemi** [comment]
@hackel +1

**Comment by whitesiroi** [comment]
How to disable it by default for all files?

let strip_whitespace_on_save = 0  <-- didn't work, still it deletes spaces.
also tried ToggleStripWhitespaceOnSave  <-- still it deletes spaces.
