### ISSUE TITLE
git-compatible whitespace checking?

### ISSUE THREAD

**Issue by ringerc** [ntpeters/vim-better-whitespace#26]
Hi

This plugin is quite handy as it stands. I'm curious about what might be involved in adding support for mixed whitespace/tab indent detection a-la `git log --check` though. It's a source of irritating whitespace issues that I have to go through and fix up afterwards if I accidentally introduce them.

I can find them with `:set list` but of course that's cumbersome to edit with always enabled, and doesn't highlight just problems.

Do you think that's likely to be possible/practical? I'm not sure how to usefully express it as a highlight expression.

**Comment by ntpeters** [comment]
I feel like this is a bit outside the scope of this plugin.  There are other plugins that report errors related to mixed indentation. I believe [Syntastic](https://github.com/scrooloose/syntastic) may report this as well?
