### ISSUE TITLE
Hide visualization of tabs before the line

### ISSUE THREAD

**Issue by Thanatermesis** [ntpeters/vim-better-whitespace#27]
There's a lot of source codes that uses tabs before the sentence, most of the times we are not authorized to rewrite the source files "as you think that is better", so it becomes annoying to visualize them

I have read the docs but i don't see any option for disable these ones (and only show the trailing ones), is it possible to do it? Can you add this option?

Thank you

**Comment by ntpeters** [comment]
This plugin does not display whitespace at the beginning of lines unless the line consists only of whitespace.  I would look at other settings/plugins you may be using that could be displaying these preceding characters.
