### ISSUE TITLE
Feature request: jump to next trailing white space

### ISSUE THREAD

**Issue by timfeirg** [ntpeters/vim-better-whitespace#32]
I think at least for folks using better-whitespace, the only place where the code would actually contain trailing whitespace (and be highlighted) is the lines that they are currently working on, so I figured it could be nice if there's a command that would allow one to quickly jump to highlighted whitespace in normal mode using `:GoToNextTrailingWhitespace`, that way one can quickly jump to trailing whitespaces in his code, which is exactly he's bee working on.
#### step 1

``` python
def func1():
    return 23

def func2():
    # I'm just going to write a = func1()
    # but I decide that there's something wrong with func1
    # so I'm going to go back and fix func1 before I finish this line
    # while leaving the following line a highlighted whitespace
    a =◼︎
```
#### step 2

``` python
def func1():
    # I now navigate to func1 to fix what's wrong
    # and note that func1 may be actually so far away that 
    # pressing `ctrl o` cannot take me back to func2
    return 42
    # now that func1 is fixed, I can use `:GoToNextTrailingWhitespace` to quickly jump to func2 (rather than pressing `ctrl o` for so many times
    # and continue to work with variable `a`


def func2():
    a =◼︎
```

**Comment by ntpeters** [comment]
While I don't see this as something I would personally use, if you were to throw a pull request my way I would likely accept it.

**Comment by sstallion** [comment]
+1 to this. This can be simulated using search, but I'd really like to use `[w` and `]w` to jump to each infraction.
