### ISSUE TITLE
Regression in support for ignoring some filetypes, e.g. vimfiler

### ISSUE THREAD

**Issue by hermes85pl** [ntpeters/vim-better-whitespace#34]
The fix for #21 introduced a regression: having configured vim-better-whitespace to ignore "vimfiler" filetype, I get all the trailing whitespace highlited when opening a vimfiler buffer for the first time by calling ":VimFiler -explorer" (this does not happen after closing the window and calling it again).

**Comment by Shougo** [comment]
Confirmed.

```vim
autocmd BufWinEnter * call <SID>SetupAutoCommands()
```

It should be:

```vim
autocmd BufWinEnter,FileType * call <SID>SetupAutoCommands()
```

Because, when the plugins create the buffers, &filetype and &buftype are not set.

It is patchwork config until it is fixed.

```vim
autocmd FileType vimfiler match ExtraWhiteSpace ''
```

**Comment by ntpeters** [comment]
Nice catch on this, thanks!  Fix is merged in.
