### ISSUE TITLE
Default doesn't seem to turn on

### ISSUE THREAD

**Issue by ajfisher** [ntpeters/vim-better-whitespace#40]
After installing this using vundle, in order to get the highlighting to work I have to run `:ToggleWhitespace` twice. The first does nothing (presumably turning it off) and the second turns it on again. 

This appears to be per-buffer behaviour as well that I have to do it rather than globally having it on or off.

I'm using powerline as well as solarized for themes (no real configuration of these beyond setting them).

Config below for any insights what may be conflicting:

```
"--- .vimrc
"--- Requires:
"----   Vundle (https://github.com/gmarik/vundle)
"---    Powerline (http://lokaltog.github.com/powerline)
"----       Used Ubuntu Mono font for Powerline. (added to repo)
"----       Used Patched monaco font for Mac
"----          https://gist.github.com/baopham/1838072
"
set nocompatible    


set t_Co=256

syntax on

filetype plugin indent on

set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set number
set numberwidth=4
set showcmd
set showmatch
set ignorecase
set hlsearch
set laststatus=2
set showtabline=2
set cursorline
set smarttab
set colorcolumn=80 " puts line at 80 char
set pastetoggle=<F2>
set bs=indent,eol,start "-- Backspace over everything in insert mode

"--------Cold folding --------------------
set foldmethod=indent
set foldlevel=99


"---- Other config ----------------
let mapleader = ","

let os = substitute(system('uname'), "\n", "", "")

"----   Set up all the vundle stuff
filetype off " required!

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
Plugin 'gmarik/Vundle.vim'

" Install relevant bundles.
Plugin 'tpope/vim-fugitive'
Plugin 'Lokaltog/powerline'
Plugin 'altercation/vim-colors-solarized'
Plugin 'ntpeters/vim-better-whitespace'

call vundle#end()

filetype plugin indent on     " required!

"----   Other config

"---- Add custom syntax handling
au BufRead,BufNewFile *.pde set filetype=arduino
au BufRead,BufNewFile *.ino set filetype=arduino

"---- Powerline -------------------------------------------------------
set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim
let g:Powerline_symbols = 'fancy'
let g:Powerline_colorscheme = 'solarized256'

"----   Solarized
colorscheme solarized
set background=dark

set noshowmode "-- remove the bottom insert thingy
```

**Comment by johngrogan** [comment]
I found this problem too.

Removing line 197 in better-whitespace.vim
```vim
autocmd BufWinEnter,FileType * call <SID>SetupAutoCommands())
```
Makes it work correctly for me.

**Comment by ajfisher** [comment]
That's in the bundle folder presumably?

**Comment by ajfisher** [comment]
Just tested after finding that file and yep works for me too....

**Comment by johngrogan** [comment]
Actually, it looks like that the fix for this issue https://github.com/ntpeters/vim-better-whitespace/issues/34 is causing the problem.

Reversing this change makes it work for me.

Unfortunately, I don't quite understand what this was fixing, or know enough about vim scripts to suggest an alternative.

**Comment by assembler** [comment]
Unti this is fixed, you can put following lines in your .vimrc:

```
autocmd VimEnter * DisableWhitespace
autocmd VimEnter * EnableWhitespace
```

This worked for me.

**Comment by jamesrward** [comment]
As @johngrogan suggested reverting 60b660cf6f2849b384096cda88eb8ec2b115c08a from #34 has this back to working as expected for me.

**Comment by domidimi** [comment]
What's the status here?

**Comment by ntpeters** [comment]
Fixed in #42

**Comment by rougeth** [comment]
Hello people, I just found out about `vim-better-whitespace`, it's an awesome plugin, thanks!

I'm having the same problem described in this issue, I need to run `:EnableWhitespace` to make it work even with settings defined on `.vimrc`:
```vim
let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1
```

Could you help me find what I'm doing wrong?

**Comment by Cimbali** [comment]
Hi @rougeth, what filetype(s) do you encounter problems with?
