### ISSUE TITLE
whitespace still there?

### ISSUE THREAD

**Issue by jayceekay** [ntpeters/vim-better-whitespace#43]
after running `:StripWhitespace` and `:ToggleWhitespace`, there seems to be whitespace remaining that's also not being highlighted. i moved the setting of my highlight color in my `.vimrc` to the end of the file, just in case.

<img width="574" alt="screen shot 2016-04-20 at 3 02 37 pm" src="https://cloud.githubusercontent.com/assets/1119866/14687013/60194364-0709-11e6-8e13-ac5b0eaafa7c.png">

**Comment by ntpeters** [comment]
Could you try `set listchars=trail:.` and see if that shows spaces at the end of the line? Each one should be displayed as a `.` after that.  I'm honestly not sure what could be causing this, so I just want to rule out it being a potential weird display issue.

**Comment by jayceekay** [comment]
that actually doesn't seem to change anything. this is what i'm seeing after running `set listchars=trail:.`

<img width="555" alt="screen shot 2016-05-17 at 8 16 37 pm" src="https://cloud.githubusercontent.com/assets/1119866/15343623/50888e50-1c6c-11e6-8112-c29ec48f962e.png">

<img width="540" alt="screen shot 2016-05-17 at 8 16 44 pm" src="https://cloud.githubusercontent.com/assets/1119866/15343626/5448f764-1c6c-11e6-9ec6-d1a679d93617.png">

lines 88, 99, 100, and 114 should all have whitespace on them, but the plugin isn't marking the first 3.

**Comment by ntpeters** [comment]
Sorry, forgot that you need to also `set list` prior to setting `listchars`. Try that and see what you get.

Could you also try manually calling the regex to strip whitespace, to see if that works on its own: `0,$s/\s\+$//e`

**Comment by jayceekay** [comment]
i guess what this comes down to is what character ` ` is. it refuses to be caught by that regex which i suppose means it is not a "whitespace character". i tried revealing it in the character viewer on OS X to no avail. `set list` shows it as a space, which should mean it's just a plain space. mysterious!

**Comment by jayceekay** [comment]
so it was NonText characters! i changed my listchars to this: set `listchars=nbsp:¬,eol:¶,tab:>-,extends:»,precedes:«,trail:•`

the violator was `nbsp`, which i think was because that was code i had copy/pasted from some documentation on the web.

i'd like to submit a pull request to maybe catch these cases but i'm not sure what the best way would be. the regex could be changed to something like `([^\x00-\x7f]|\s)\+$` but i wasn't able to get it to highlight those nbsps.

**Comment by ntpeters** [comment]
This has now been fixed in 67564d2 with support for all unicode whitespace characters.

**Comment by jayceekay** [comment]
👍
