### ISSUE TITLE
No whitespace highlighting when opening a split on the same buffer

### ISSUE THREAD

**Issue by sjmelia** [ntpeters/vim-better-whitespace#45]
Thanks for your work on this project!

I've encountered a small problem when opening a split on an existing buffer - the BufWinEnter event doesn't fire. (As expected from the docs [here](http://vimdoc.sourceforge.net/htmldoc/autocmd.html#BufWinEnter)) To replicate:

1. Open a file with trailing whitespace (it'll be highlighted)
2. Create a split on the same buffer with sp

Expected: the new split will also contain highlighted whitespace
Actual: the split does not highlight the whitespace.

**Comment by ntpeters** [comment]
Ah, good catch. Turns out #42 just introduced this by removing the `WinEnter` event. I totally missed that when I merged it in. I added a couple of notes on your PR.

**Comment by ntpeters** [comment]
Fixed in #46
