### ISSUE TITLE
No trailing space notification with lightline.vim

### ISSUE THREAD

**Issue by jjo93sa** [ntpeters/vim-better-whitespace#50]
I've installed the plugin and it is highlighting trailing white space just fine. However, I'm also using lightline.vim, https://github.com/itchyny/lightline.vim, and I don't get the "trailing [n]" notification in the right hand side of the status line. Do I need to configure something?

**Comment by ntpeters** [comment]
To my knowledge lightline doesn't have trailing whitespace warnings built in like Airline does, and it's something you need to add yourself.  Had you set this up with lightline previously, and it stopped working after enabling this plugin?

**Comment by jjo93sa** [comment]
No, this is a new install. I've been trying to find a good set of plugins and swapped from airline to lightline. I'll see if I can figure it out & let you know.

**Comment by ntpeters** [comment]
Okay, then I'll close this issue, as it is unrelated to this plugin.
