### ISSUE TITLE
Option to show (leading) tabs

### ISSUE THREAD

**Issue by varac** [ntpeters/vim-better-whitespace#60]
I'd like to have the option to show leading tabs (or even all tabs).
Please consider including this feature.

**Comment by 0xC0FFEE** [comment]
I'd second this. It'd be great if leading tabs/spaces could also be highlighted. 

I work on different projects with different indentation rules. Highlighting leading spaces (when tabs should be used for indentation) sounds like a nice addition. Or vice versa: if all indentations should be performed with spaces, leading tabs would make good candidates for highlighting.

**Comment by mboughaba** [comment]
Hi guys, 
This can be done using vanilla ViM list feature.
```vim
set list
```
Will highlight all white-spaces characters.
to make a fancy list display add the follwing to `.vimrc`
```vim
" Customized characters to be shown when list is on
se listchars=tab:▸\ ,trail:·,extends:❯,precedes:❮,nbsp:⎵,eol:¬
```
to disable it
```vim
set nolist
```
I made a plugin which does that, you may give it a try and drop me some feedback
https://github.com/mboughaba/vim-lessmess

Cheers,
Mo

**Comment by ntpeters** [comment]
@varac: Yeah, as @mboughaba mentioned the list feature in Vim is pretty flexible, and is what I personally use for displaying tabs.

@0xC0FFEE: I just merged in a change that allows highlighting spaces before/between tabs. I think that combined with using list might get you most of the way there for your scenario.

Closing, as list should be sufficient for this.
