### ISSUE TITLE
Feature: Option to Ignore whitespace only lines

### ISSUE THREAD

**Issue by oxinabox** [ntpeters/vim-better-whitespace#65]
I often have blank lines containing only the whitespace from the current indent (via autoindenting).
I don't want to remove/highlight these, as they are not a problem for me.

![image](https://cloud.githubusercontent.com/assets/5127634/25995376/97227d78-3744-11e7-9965-31bb6469a1b2.png)

**Comment by Cimbali** [comment]
I think adding an option that changes the pattern `s:eol_whitespace_pattern` to add a non-empty lookback at its beginning should work. I experimented with `\S\@1<=\s\+$` but you should obviously do it with the real class of supported white space characters.

See `:help /\@<=`

**Comment by xerus2000** [comment]
Fixed in #72 

Add `let g:better_whitespace_skip_empty_lines=1` in vimrc

Just for quick reference ;)
