### ISSUE TITLE
[Clarification] colorscheme in the screenshot

### ISSUE THREAD

**Issue by makefu** [ntpeters/vim-better-whitespace#66]
Hey, thanks for this plugin.
It would be great if you could also link the colorscheme and configuration of the vim setup you show in the screenshot. i am specifically interested in the colorization of the different kinds of whitespaces.

Thanks!

**Comment by ntpeters** [comment]
The colorscheme shown is [Jellybeans](https://github.com/nanotech/jellybeans.vim)

My options for displaying whitespace characters:
```
set list
set listchars=tab:▸\ ,eol:¬
"set list listchars=tab:>-,trail:.,extends:>
```

You can see the rest of my setup in my [vimrc](https://github.com/ntpeters/dotfiles/blob/master/vimrc)

**Comment by makefu** [comment]
thanks for the reply!
