### ISSUE TITLE
Feature request: add an option to remove empty lines at the end of files.

### ISSUE THREAD

**Issue by huseyinyilmaz** [ntpeters/vim-better-whitespace#67]
Hey,
First of all thank you for making this plugin. I found it very helpful.

I used emacs before and recently moved to vim. In emacs, default whitespace behavior was to remove empty spaces at the end of each line and remove empty lines at the end of files. (empty lines at the end of files considered a lint error in most languages anyway.) With this plugin, I realized that it does a great job removing whitespace but it does not remove empty lines at the end of files.

I think it would be a good addition to this library to have empty line removal as well.

**Comment by ntpeters** [comment]
That actually sounds like a great idea. I haven't had much time to work on this lately, but will add this to my todo list. Otherwise is you wanted to throw in a PR for it that'd be great too (if you do, it should be allow separate enable/disable).

**Comment by mboughaba** [comment]
Hi @huseyinyilmaz,

I've made a simple plugin which does remove empty lines at the end of files as well as trailing white-spaces and mixed-indent. Maybe you can give it a try and drop me some feedback if possible.

I hope this won't sound as pure self promotion :blush:
