### ISSUE TITLE
Highlighting of mixed indent (tabs after spaces)

### ISSUE THREAD

**Issue by blueyed** [ntpeters/vim-better-whitespace#7]
Mixed indent (tabs after spaces) can be matched using `\+\ze\t`.

It would be nice to have a separate syntax group for it (because it's not "extra" whitespace), and a way to enable/disable it via configuration.

**Comment by frivoal** [comment]
Indent Guides does way more than what I want, and your plugin is much closer to what I'd like. But
I agree with @blueyed that spaces before tabs would be good to highlight: they're pretty much always a mistake (tabs before spaces not necessarily).
