### ISSUE TITLE
Feature: Option to not show trailing whitespace.

### ISSUE THREAD

**Issue by dylan-chong** [ntpeters/vim-better-whitespace#71]
If I know that the white spaces are going to be removed on save, then I don't need to see that whitespace exists.

Therefore it would be good to have an option not to highlight the trailing whitespace

**Comment by Cimbali** [comment]
I think doing this in your vimrc should work:

    let g:better_whitespace_enabled = 0
    let g:strip_whitespace_on_save = 1
