### ISSUE TITLE
buftype=nofile still being hightlighted

### ISSUE THREAD

**Issue by spinningarrow** [ntpeters/vim-better-whitespace#76]
I have a preview buffer open, which has some whitespace issues. I think https://github.com/ntpeters/vim-better-whitespace/commit/bf6d1ecda84c945b7d7cd2746b388f8e4f10f350 is supposed to skip highlighting in this buffer, but I still see it:

![image](https://user-images.githubusercontent.com/1797328/36070804-d7831612-0f3d-11e8-82e2-f3e296cc3959.png)

In the screenshot above, the `[Scratch][-][Preview]` buffer is the active one, and I have just executed `set buftype?` in that buffer.

**Comment by Cimbali** [comment]
That's interesting, how do you open a scratch buffer? It seems to me setting buftype=nofile is something that happens some time after opening the buffer. As long as you don't recycle another buffer the `buftype` should still be detected OK. I couldn't reproduce using [scratch.vim](https://vim.sourceforge.io/scripts/script.php?script_id=664).

However, if you had a buffer that has a filetype for which we should highlight, and *only after the FileType event* the `let buftype=nofile` is called, then the buffer should still be highlighted.

Whether or not to highlight a buffer is saved per-buffer in `b:better_whitespace_enabled`, can you check its value?

**Comment by spinningarrow** [comment]
`b:better_whitespace_enabled` is set to `1` in that buffer.

It is opened by https://github.com/tpope/vim-fireplace when I type in a function name in my actual vim buffer. The scratch buffer then shows the definition of that function.

**Comment by Cimbali** [comment]
I don't have that plugin and don't use clojure so that's going to be hard to reproduce. But would it by any chance be the completion preview window? Does the window stop appearing if you do `set completeopt-=preview` ?

**Comment by spinningarrow** [comment]
Yep, I do believe that is the completion preview window!
