### ISSUE TITLE
Just updated, space doesn't function properly in normal mode

### ISSUE THREAD

**Issue by tudurom** [ntpeters/vim-better-whitespace#78]
So I just updated all the plugins on my system. I have `<Space>` set as leader so space being broke in normal mode is a major bummer for me. I have `showcmd` set, so I can see in the gutter the keystrokes for different commands. One thing that I noticed is that all the commands that are bound to some key combination that includes the leader key don't work. When I pressed space, the gutter would show `<20>` instead of `\` as it normally does for space. Trying to track down the problem, I disabled each plugin I use one by one until I disabled this one. The problem magically disappeared. Then, I re-enabled all the plugins except this one and again, everything worked! So it should be a problem with this plugin, right?

**Comment by ntpeters** [comment]
Ah, yeah there was a recent change to add an operator to this plugin, which by default is bound to `<space>`. You can rebind or disable it with: `let g:better_whitespace_operator = ''`.

**Comment by bulletmark** [comment]
Sorry, @ntpeters, but I think this is a poor change. I just spent quite a while trying to work out why my vim was so oddly broken today until I eventually narrowed it to this plugin and then found this bug. I suspect a flood of others will arrive here also. I urge you to reconsider choosing such a generic operator.

**Comment by ntpeters** [comment]
Yeah, that may not have been the best choice, but nothing better came to mind when I was merging that in and I completely overlooked the fact that `<space>` is a pretty common remap of `<leader>` (among other things). Sorry about the trouble... 😢

What do you think of something like: `<leader>s<space>`? I haven't commonly seen `<leader>s` used, and this is similar to the pattern NerdCommenter uses (at least for one of its bindings).
I'm completely open to suggestions!

**Comment by pirminis** [comment]
can confirm this broke vim space/leader keybinds a little.

`let g:better_whitespace_operator = ''` helped. maybe set this option to this (empty value) by default?

**Comment by ntpeters** [comment]
I just merged in an update to change the default operator to `<leader>s`, and to only apply the mappings if another mapping does not already exist for the given operator. This should ensure the defaults are non-intrusive to existing setups.

**Comment by bulletmark** [comment]
I updated and deleted my `let g:better_whitespace_operator = ''` line to confirm this is fixed. Thanks.
