### ISSUE TITLE
Error on opening Vim with a new file

### ISSUE THREAD

**Issue by rphes** [ntpeters/vim-better-whitespace#87]
Apparently similar to #86, encountered at de6caab.

I have these lines in my `init.vim` for Neovim:
```vim
let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1
autocmd FileType markdown DisableWhitespace
```

Upon opening a new file with `nvim test.md`, I get:

```
"test.md" [New File]
Error detected while processing function <SNR>72_DisableWhitespace:
line    1:
E121: Undefined variable: b:better_whitespace_enabled
E15: Invalid expression: b:better_whitespace_enabled != 0
```

**Comment by Cimbali** [comment]
Can you try adding markdown to the blacklist instead of deactivating it with an autocmd?

**Comment by Cimbali** [comment]
You want to enable stripping whitespace on save but not displaying it?

**Comment by rphes** [comment]
Correct. I also think this is the behaviour of most IDEs/editors that implement some sort of stripping functionality.
